#!/usr/bin/env node

const metrics = require('commander');
const client = require('./lib/client_metrics');
const psi = require('./lib/psi');
const table = require('markdown-table');
const server = require('./lib/serverMetrics');

metrics
    .version('1.5.0')
    .option('-m, --mobile', 'Use mobile user agent')
    .option('--psi', 'Run Page Speed Insights')
    .option('--psi-key [psiKey]', 'Page Speed Insights API key')
    .option('--control [control]', 'Specify the URL to be used as the control to compare against')
    .option('--target [target]', 'Specify the URL to be used as the target of the comparison')
    .parse(process.argv);

if (!process.argv.slice(2).length) {
    metrics.outputHelp();
}

async function gatherMetrics(url) {
    const options = {isMobile: metrics.mobile,
                     key: metrics.psiKey};
    const clientMetrics = await client.collect(url, options);
    const pageMetrics = clientMetrics.page;
    const serverMetrics = await server.collect(url, metrics.mobile);

    const psiData = {};
    const psiScore = {};
    const psiPageStats = {};

    if (metrics.psi) {
        psiData = await psi.collect(url, options);

        psiScore = psiData.ruleGroups.SPEED.score;
        psiPageStats = psiData.pageStats;

        for (let k in psiPageStats) {
            psiPageStats[k] = parseInt(psiPageStats[k]);
        }
    }

    return {
        pageMetrics: pageMetrics,
        psiScore: psiScore,
        psiPageStats: psiPageStats,
        nodeCountServer: serverMetrics.nodeCount,
        documentLength: serverMetrics.length
    };
}

function computeDelta(control, target) {
    let delta = {};

    for (let k in control) {
        delta[k] = target[k] - control[k];
    }

    return delta;
}

async function doIt(controlUrl, targetUrl) {
    let control = await gatherMetrics(controlUrl);
    let target = await gatherMetrics(targetUrl);

    let delta = {pageMetrics: computeDelta(control.pageMetrics, target.pageMetrics),
                 psiScore: control.psiScore - target.psiScore,
                 nodeCountServer: control.nodeCountServer - target.nodeCountServer,
                 documentLength: control.documentLength - target.documentLength,
                 psiPageStats: computeDelta(control.psiPageStats, target.psiPageStats)};

    let metricsTable = [['Metric', 'Control', 'Target', 'Delta'],
                        ['Client Side', '', '', ''],
                        ['DOM Content Loaded (ms)', control.pageMetrics.dcl, target.pageMetrics.dcl, delta.pageMetrics.dcl],
                        ['Interactive (ms)', control.pageMetrics.interactive, target.pageMetrics.interactive, delta.pageMetrics.interactive],
                        ['DOM Complete (ms)', control.pageMetrics.domComplete, target.pageMetrics.domComplete, delta.pageMetrics.domComplete],
                        ['Load (ms)', control.pageMetrics.load, target.pageMetrics.load, delta.pageMetrics.load],
                        ['Paint (ms)', control.pageMetrics.paint, target.pageMetrics.paint, delta.pageMetrics.paint],
                        ['DOM Nodes', control.pageMetrics.nodeCount, target.pageMetrics.nodeCount, delta.pageMetrics.nodeCount],
                        ['Server Side', '', '', ''],
                        ['DOM Nodes', control.nodeCountServer, target.nodeCountServer, delta.nodeCountServer],
                        ['Document Length (bytes)', control.documentLength, target.documentLength, delta.documentLength]];

    let psiMetricsTable;

    if (metrics.psi) {
        psiMetricsTable = [['Page Speed Insights', '', '', ''],
                           ['PSI Score (0/100)', control.psiScore, target.psiScore, delta.psiScore],
                           ['Number of Hosts', control.psiPageStats.numberHosts, target.psiPageStats.numberHosts, delta.psiPageStats.numberHosts],
                           ['Number of Resources', control.psiPageStats.numberResources, target.psiPageStats.numberResources, delta.psiPageStats.numberResources],
                           ['Number of Static Resources', control.psiPageStats.numberStaticResources, target.psiPageStats.numberStaticResources, delta.psiPageStats.numberStaticResources],
                           ['Total Request Bytes', control.psiPageStats.totalRequestBytes, target.psiPageStats.totalRequestBytes, delta.psiPageStats.totalRequestBytes],
                           ['HTML Response Bytes', control.psiPageStats.htmlResponseBytes, target.psiPageStats.htmlResponseBytes, delta.psiPageStats.htmlResponseBytes],
                           ['CSS Response Bytes', control.psiPageStats.cssResponseBytes, target.psiPageStats.cssResponseBytes, delta.psiPageStats.cssResponseBytes],
                           ['JS Response Bytes', control.psiPageStats.javascriptResponseBytes, target.psiPageStats.javascriptResponseBytes, delta.psiPageStats.javascriptResponseBytes],
                           ['Image Response Bytes', control.psiPageStats.imageResponseBytes, target.psiPageStats.imageResponseBytes, delta.psiPageStats.imageResponseBytes],
                           ['Other Response Bytes', control.psiPageStats.otherResponseBytes, target.psiPageStats.otherResponseBytes, delta.psiPageStats.otherResponseBytes],
                           ['Number JS Resources', control.psiPageStats.numberJsResources, target.psiPageStats.numberJsResources, delta.psiPageStats.numberJsResources],
                           ['Number CSS Resources', control.psiPageStats.numberCssResources, target.psiPageStats.numberCssResources, delta.psiPageStats.numberCssResources]]
    }

    let resultsTable = table([].concat.apply([], [metricsTable, psiMetricsTable]).filter(x => x));
    const platform = metrics.mobile ? 'Mobile' : 'Desktop';

    console.log('Results of ' + controlUrl + ' vs. ' + targetUrl + ' on ' + platform);
    console.log();
    console.log(resultsTable);
}

doIt(metrics.control, metrics.target);
